package javaapplication3;
// Generated 12-Mar-2017 19:35:24 by Hibernate Tools 4.3.1



/**
 * Customer generated by hbm2java
 */
public class Customer  implements java.io.Serializable {


     private int customerId;
     private String name;

    public Customer() {
    }

	
    public Customer(int customerId) {
        this.customerId = customerId;
    }
    public Customer(int customerId, String name) {
       this.customerId = customerId;
       this.name = name;
    }
   
    public int getCustomerId() {
        return this.customerId;
    }
    
    public void setCustomerId(int customerId) {
        this.customerId = customerId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }




}


