package javaapplication3;
// Generated 12-Mar-2017 19:35:24 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Mysession generated by hbm2java
 */
public class Mysession  implements java.io.Serializable {


     private int sessionId;
     private Date date;
     private Date startTime;
     private Date endTime;

    public Mysession() {
    }

	
    public Mysession(int sessionId) {
        this.sessionId = sessionId;
    }
    public Mysession(int sessionId, Date date, Date startTime, Date endTime) {
       this.sessionId = sessionId;
       this.date = date;
       this.startTime = startTime;
       this.endTime = endTime;
    }
   
    public int getSessionId() {
        return this.sessionId;
    }
    
    public void setSessionId(int sessionId) {
        this.sessionId = sessionId;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public Date getStartTime() {
        return this.startTime;
    }
    
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }
    public Date getEndTime() {
        return this.endTime;
    }
    
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }




}


