
import java.util.List;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : BookingApplication
//  @ File Name : Sarah

//  @ Date : 06/03/17
//  @ Author : 
//
//




public class SlopeOperatorUI {
	private BookingController control;

    public SlopeOperatorUI() {
        control=BookingController.getInstance();
    }
        
        
	public int MakeBoking(int custid,int sessiontype,int sessionid) 
        {
            return control.MakeBooking(custid,sessiontype,sessionid);
	}
        public String viewcustomer(int id) 
        {
            return control.viewCustomer(id);
	}
        public List viewSchedule()
        {
            return control.viewSchedule();
        }
}
